{% set name = "blobfile" %}
{% set version = "3.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 78514a9265b9aa7d4607042dc77c5e6461ab27036450ad8e1f6ef9a7f29bf958

build:
  number: 0
  skip: true  # [py<310]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - python
    - pip
    - setuptools >=69
  run:
    - python
    - pycryptodomex >=3.8
    - urllib3 >=2
    - lxml >=4.9
    - filelock >=3.0

test:
  imports:
    - blobfile
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/blobfile/blobfile
  license: Unlicense
  license_family: Other
  license_file: LICENSE
  summary: Read GCS, ABS and local paths with the same interface
  description: |
    blobfile is a Python library for reading and writing files on local disk,
    Google Cloud Storage (GCS), and Azure Blob Storage (ABS) with a single,
    unified interface compatible with Python's built-in file I/O.
  doc_url: https://github.com/blobfile/blobfile
  dev_url: https://github.com/blobfile/blobfile

extra:
  recipe-maintainers:
    - BastianZim
    - xkong-anaconda
